# Generated by Django 5.2.7 on 2026-02-08 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='تصویر')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ آپلود')),
                ('has_vehicle', models.BooleanField(default=False, verbose_name='دارای خودرو')),
                ('vehicle_count', models.IntegerField(default=0, verbose_name='تعداد خودرو')),
                ('detection_result', models.JSONField(blank=True, null=True, verbose_name='نتیجه تشخیص')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/%Y/%m/%d/', verbose_name='تصویر پردازش شده')),
            ],
            options={
                'verbose_name': 'تصویر آپلود شده',
                'verbose_name_plural': 'تصاویر آپلود شده',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
